### ISSUE TITLE
Drop down options 

### ISSUE THREAD

**Issue by Kenyatha** [cgkineo/adapt-articleBlockSlider#15]
Drop down menus within components--for example matching question answer options--do not open when using article Block Slider.  Is there a solution for this or is there a particular setting that would allow functionality?  Thanks!

**Comment by moloko** [comment]
Does appear to be a bug. Tried both the old and new matching components just in case that would make any difference but it doesn't.

**Comment by moloko** [comment]
@Kenyatha I've just tried this again with the latest version of the matching component (v2.1.4) and it works fine now - I suspect it was fixed in matching v2.1.2 by https://github.com/adaptlearning/adapt_framework/issues/1543
