### ISSUE TITLE
Navigation buttons fly in from bottom

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-articleBlockSlider#24]
When the learners loads the page they see the nav buttons animate in from the bottom. Would be better to just disable animations until the page has fully loaded.
 
![b8ey2vjprk](https://user-images.githubusercontent.com/1676635/29021080-44346fca-7b5c-11e7-8536-0610378213a2.gif)

**Comment by oliverfoster** [comment]
no longer supported
