### ISSUE TITLE
Slider-trickle completion issue

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-articleBlockSlider#26]
Love this extension but just now experiencing an issue since upgrading my authoring tool. Where I have multiple blocks in a slider, all non-optional, the trickle Continue button consistently goes active on the 2nd last block viewed instead of the last. e.g. where there are 2 required blocks in an article, trickle enables on the 1st instead of 2nd; where there are 3 blocks, trickle enables on the 2nd block viewed instead of 3rd, etc. 
Any ideas what might be the cause? 
.. Just worked out that the issue occurs on full width components only. Where there's 2 components per block trickle responds fine. I was testing on the original Vanilla theme using Chrome.

**Comment by oliverfoster** [comment]
This is an ongoing saga to do with a library called "inview" and the completion of the components inside the article block slider. Trickle listens to the completion of the components and isn't aware that they're in an ABS.

I imagine that all of your components are text + graphics? Or that the second to last component requires some interaction? Perhaps you can list the components in one of your broken examples?

Could you also let me know which framework, trickle, and ABS versions you're using?

**Comment by barryjenkin** [comment]
I was using just text components (single full width) in each block to get the trickle behaviour on the 2nd last. No interactivity. It also happens when all components are a full width graphic. Interesting though that it works correctly where I have graphics + text (2 components) per block. Trickle 2.1.3, ABS 2.0.3. I can't see my framework version at the moment .. it's whatever was current at 26th June.

**Comment by oliverfoster** [comment]
Ta, will try and see if I can replicate a bit later on today.

**Comment by barryjenkin** [comment]
Another thing I noticed - which might provide a clue as to what's happening - is that if I jump straight to whatever the 2nd last or last selection is, it tells trickle all is complete. e.g. if I have 4 tabs all set to required, selecting only the 3rd (skipping the 2nd) makes trickle go active. Same behaviour if I select the 4th only.

**Comment by barryjenkin** [comment]
Hey Oliver. Did you end up finding a solution to this? I've been using it quite a lot and hoping to update.

**Comment by oliverfoster** [comment]
Nope, I'm afraid I haven't had a look yet, I've fixed a load of bugs in jquery.onscreen. Can you still reproduce this bug with the latest framework?

**Comment by barryjenkin** [comment]
omg it's working on the new 0.4.0. my life is complete.
