### ISSUE TITLE
Trickle only listening for completion on last tab

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-articleBlockSlider#29]
I've got this working well in the arrows format but tabs is letting me 'cheat' by skipping to the last tab to enable trickle. I've made sure content in all tabs is non-optional and it still lets me skip ahead. Is there a simple fix for this one? I've been testing in the latest authoring tool with 2.0.3 version of the extension.

**Comment by moloko** [comment]
what content have you got in your blocks? content that relies on inview to detect completion can be a problem within article-block-slider

**Comment by barryjenkin** [comment]
Just image and/or text using the graphic & text components. Does this mean it's relying on inview? I kind of want it to behave the same way as Narrative where completion is based on all slides viewed.

**Comment by moloko** [comment]
@barryjenkin articleBlockSlider doesn't have its own completion, it's the components you use within it that handle this. ABS is basically just a different way of presenting the content.

Sounds like you might be better of with something like [adapt-tabs](https://github.com/cgkineo/adapt-tabs)
