### ISSUE TITLE
rtl in Firefox, Safari: current block not displayed

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-articleBlockSlider#33]
rtl ('dir-rtl') works fine in Chrome, but not in Firefox and Safari. In these (others not tested) the current block is not displayed. It is not improperly styled as 'visibility=hidden'. It is because the current block is not scrolled into view. Apparently there is a dispute among browsers about how rtl should be interpreted and this impacts what scrollLeft returns: positive vs negative numbers.

**Comment by oliverfoster** [comment]
no longer supported
