### ISSUE TITLE
Issues when using articleBlockSlider with Trickle

### ISSUE THREAD

**Issue by kineopete** [cgkineo/adapt-articleBlockSlider#4]
Chuck has identified a number of issues when using aBS with Trickle - please see the attached PDF for details.

[trickle-and-blockSlider_01.pdf](https://github.com/cgkineo/adapt-articleBlockSlider/files/9891/trickle-and-blockSlider_01.pdf)

**Comment by oghmios** [comment]
Can I rewrite the code to use the slide buttons like a trickle button? Activate and deactivate when you pass the block.

**Comment by oliverfoster** [comment]
You can clone and make any changes you wish. If you want to push the changes you've made back in, you might want to make it a set of optionals rather than changing entirely.

**Comment by hbaileylxd** [comment]
OMG it works with the Authoring Tool now I LOVE YOU GUYS!!! Thanks @mike-st

**Comment by mike-st** [comment]
No Problem! Love getting components and extensions working in the authoring tool. It is so nicely built. I just got another component working in the authoring tool. The drag and drop one. Take a look if your interested...
https://github.com/mike-st/adapt-dragAndDrop

**Comment by hbaileylxd** [comment]
OMG I can't take any more of this AWESOMENESS!!!!!!! _BLAM!_

**Comment by hbaileylxd** [comment]
Mike I can't seem to add issues/comments to drag and drop but I do have some thoughts ....

**Comment by mike-st** [comment]
Hey I am not the original author of this component as I just forked it from BATraining/adapt-dragAndDrop and got it working in the authoring tool along with other functionality changes. You can write your issues and thoughts if you like on the BATraining/adapt-dragAndDrop page here is the link below... 

https://github.com/BATraining/adapt-dragAndDrop/issues

**Comment by mldaq** [comment]
Hi, I've looked at many of the comments and the pdf submitted by Pete and not sure if this is a new issue with v4 framework. I am using the Article BlockSlider and Trickle and having issues. We have two articles and the article blockslider on both. We want to hide the second set of blockslider content until the first set is complete. We are working in the authoring tool and have tried many different options and nothing seems to hide the second article.
