### ISSUE TITLE
Get the number of the block

### ISSUE THREAD

**Issue by oghmios** [cgkineo/adapt-articleBlockSlider#5]
hi, I wanna know the number of the current block in another extension. I do that method:
_getCurrentBlock: function(){
            var a = this.model.get("_currentBlock");
            return a;
        }

but when i call this method form outside, I recive the entire block, and I only want a number, it is possible?

Thank you for all

**Comment by oliverfoster** [comment]
Yea, that should work. you must be doing something else wrong. _currentBlock only ever stores a number.

**Comment by oghmios** [comment]
I do this for example in another extension

var b = Adapt.trigger("_getCurrentBlock");
console.log(b);

And that shows [object Object]

If I put for example

var c=1;
if(c==b) alert('');

the alert don't show me never, that is my problem

**Comment by oliverfoster** [comment]
yea, Adapt.trigger doesn't work like that. You'll need to read > http://backbonejs.org/#Events < this first so you can understand how Backbone View, Model and Collection events work. Let me just see if I can figure out what you need.. give me a few minutes.

**Comment by oliverfoster** [comment]
You'd probably be better off to use the Article's model.

Something like:

```
Adapt.findById("a-05").get("_currentBlock");

```

**Comment by oghmios** [comment]
Yes! That is perfect, thank you for all!!!

Do you have any complete documentation for programming in adapt?

**Comment by oghmios** [comment]
Yes! Thank you for all!!

**Comment by oghmios** [comment]
...
