### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-articleBlockSlider#51]
Hello

When this plugin is added I keep getting the following error, the course previews fine without the plugin added to the course:

Command failed: grunt server-build:prod --outputdir=courses/5f6c6871010e4a0306ac5270/5f6c86cf5f46340277f0c487/build --theme=5f6c697a010e4a0306ac528b --menu=adapt-contrib-boxMenu

Fatal error: {
 "message": "variable @block-padding-top is undefined",
 "type": "Name",
 "filename": "src/extensions/adapt-articleBlockSlider/less/articleBlockSlider-article.less",
 "index": 172,
 "line": 6,
 "column": 12,
 "callLine": null,
 "extract": [
  "\t\t\tmax-width: @device-width-large;",
  "\t\t\tpadding: @block-padding-top 0 @block-padding-bottom;",
  "\t\t\t// reduce padding as screen width decreases"
 ]
}

**Comment by moloko** [comment]
@fosterc1 this plugin hasn't had an Adapt v5-compatible release yet. 

it's actually in the process of getting a much-needed re-write (see #50) - we'll probably park the v5 release until that's done - but in the meantime there is a [v5 release branch](https://github.com/cgkineo/adapt-articleBlockSlider/tree/release/v5) that you could try - just bear in mind it's a work in progress

**Comment by oliverfoster** [comment]
Master branch is now v5 compatible.
