### ISSUE TITLE
Extra tab on article trickle

### ISSUE THREAD

**Issue by marissa-champions** [cgkineo/adapt-articleBlockSlider#55]
When trickle is set at the article level, an extra empty tab is displayed requiring the user to click the tab and then the trickle button to move on. The trickle button should show up on the last block and then allow the user to move on.

**Comment by oliverfoster** [comment]
The latest version in master branch should have a fix for this already. Can you check it's up to date?

**Comment by marissa-champions** [comment]
Oops I should have checked the version first! That fixed it! Thank you!
